blog/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('posts/<slug:slug>', views.post_detail, name='post_detail_url'),
    path('register/', views.register, name='register'),
    path('login/', views.login_site, name='login_url'),
    path('logout/', views.logout_site, name='logout_url'),
    path('posts/<slug:slug>/comment', views.comment, name='comment'),
    path('categories/<slug:slug>', views.category_detail, name ='category_detail_url'),
    path('search/', views.search_function, name = 'search_url')
    path('category/', views.category, name = 'category_url',)
]

news_blog/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models
from django.utils import timezone
from django.shortcuts import reverse
from django.contrib.auth.models import User

class Post(models.Model):
    title = models.CharField('Zagolovok', max_length=255)
    text = models.TextField('Tekst Novosti')
    image = models.ImageField("Kartinka Posta", upload_to='post_img/')
    feature = models.BooleanField('v slaydere', default=False)
    category = models.ForeignKey('Category', on_delete=models.CASCADE, null=True)
    slug = models.SlugField('Ssilka', unique=True)
    created_at = models.DateTimeField('Data sozdaniya posta', default=timezone.now)

    class Meta:
        verbose_name = 'Novost'
        verbose_name_plural = "Novosti"

    def __str__(self):
        return self.title
    
    def get_link(self):
        return reverse('post_detail_url', kwargs={'slug': self.slug})
    
class Category(models.Model):    
    title = models.CharField('Nazvanie kategorii', max_length=255)
    image = models.ImageField('kartinka kategorii', upload_to='cat_img/')
    slug = models.SlugField('Ssilka',unique=True)

    class Meta:
        verbose_name = 'Kategoriya'
        verbose_name_plural = 'Kategorii'

    def __str__(self):
        return self.title 
    
class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    date = models.DateTimeField(default = timezone.now) 
    text = models.TextField()  

    class Meta:
        verbose_name = 'Komentariy'
        verbose_name_plural = 'Komentarii'

    def __str__(self):    
        return self.author.username + ' ' + self.post.title

blog/forms.py
from django.contrib.auth.forms import UserCreationForm
from django import forms
from django.contrib.auth.models import User

class RegisterForm(UserCreationForm):
    username = forms.CharField(label='Nickname', required=True, widget=forms.TextInput(attrs = {'class': "form-control mb-20"}))
    email = forms.EmailField(label='E-mail', required=True, widget=forms.TextInput(attrs = {'class': "form-control mb-20"}))
    password1 = forms.CharField(label='Parol', required=True, widget=forms.PasswordInput(attrs = {'class': "form-control mb-20"}))
    password2 = forms.CharField(label='Povtorite parol', required=True, widget=forms.PasswordInput(attrs = {'class': "form-control mb-20"}))
    first_name = forms.CharField(label='Imya', required=True, widget=forms.TextInput(attrs = {'class': "form-control mb-20"}))
    last_name = forms.CharField(label='Familiya', required=True, widget=forms.TextInput(attrs = {'class': "form-control mb-20"}))

    class Meta:
        model = User
        fields = ('username', 'email', 'first_name', 'last_name', 'password1', 'password2')

    def save(self, commit=True):
        user = super().save(commit=False)
        user.email = self.cleaned_data['email']
        user.first_name = self.cleaned_data['first_name']
        user.last_name = self.cleaned_data['last_name']
        if commit:
            user.save()
            return user

blog/views.py
from django.shortcuts import render, redirect, reverse
from .models import Post, Category, Comment
from .forms import RegisterForm
from django.contrib.auth import authenticate, login, logout
from django.db.models import Q
# Create your views here.
def index(request):
    slides = Post.objects.filter(feature = True).order_by('-created_at')[:4]
    posts = Post.objects.order_by('-created_at')[:8]
    categories = Category.objects.all()[:12]
    return render(request, 'index.html', {'posts': posts, 'slides': slides, 'categories': categories})

def post_detail(request, slug):
    post = Post.objects.get(slug__exact=slug)
    return render (request, 'post_detail.html', {'post':post})

def register(request):
    if not request.user.is_authenticated:
        if request.method == 'POST':
            form = RegisterForm(request.POST)
            if form.is_valid():
               user=form.save()
               login(request, user)
               return redirect('index')
        else:
            form = RegisterForm()    
        return render(request, 'register.html', {'form':form})    
    return redirect('index')    

def login_site(request):
    if request.user.is_authenticated:
        return redirect('index')
    message = None    
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            return redirect('index')
        else:
            message = 'IZvinite, takogo polzovatelya ne suchestvuet'    
            return render(request, 'blog/login.html', {'message': message})
    return render(request, 'login.html', {'message': message})        

def logout_site(request):    
    if request.user.is_authenticated:
        logout(request)
    return redirect('index')    

def comment(request, slug):
    if request.method == 'POST':
        comment = Comment()
        comment.post = Post.objects.get(slug__exact=slug)
        comment.author = request.user
        comment.text = request.POST.get('comment')
        comment.save()
        return redirect(reverse('post_detail_url', kwargs={'slug': slug}))
    
def category_detail(request, slug):    
    category = Category.objects.get(slug__exact=slug)
    return render(request, 'category_detail.html', {'category': category})

def search_function(request):
    query = request.GET.get('search_input')
    posts = Post.objects.filter(Q(title__iregex = query))
    return render(request, 'search.html', {'query': query, 'posts': posts})




        

blog/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %} {% endblock %}</title>
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
</head>
<body>
    <nav class="navbar navbar-expand-lg bg-body-tertiary" >
        <div class="container-fluid">
          <a class="navbar-brand" href="#">Navbar</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="#">Home</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="#">Link</a>
              </li>
              {% if not user.is_authenticated %}
              <li class="nav-item">
                <a class="nav-link" href="{% url 'register' %}">Регистрация</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'login_url' %}">Вход</a>
              </li>
              {% else %}
              <li class="nav-item">
                <a class="nav-link" href="{% url 'logout_url' %}">Вход</a>
              </li>
              {% endif %}
              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="{% url %}" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                  categories
                </a>
                <ul class="dropdown-menu">
                  <li><a class="dropdown-item" href="#">Action</a></li>
                  <li><a class="dropdown-item" href="#">Another action</a></li>
                  <li><hr class="dropdown-divider"></li>
                  <li><a class="dropdown-item" href="#">Something else here</a></li>
                </ul>
              </li>
              <li class="nav-item">
                <a class="nav-link disabled" aria-disabled="true">categories</a>
              </li>
            </ul>
            <form class="d-flex" action="{% url 'search_url' %}" role="search">
              <input class="form-control me-2" method="GET" name="search_input"  type="search" placeholder="Search" aria-label="Search">
              <button class="btn btn-outline-success" type="submit">Search</button>
            </form>
          </div>
        </div>
      </nav>
    {% block content %}

    {% endblock %} 
    

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js" integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.min.js" integrity="sha384-0pUGZvbkm6XF6gxjEnlmuGrJXVbNuzT9qBBavbLwCsOGabYfZo0T0to5eqruptLy" crossorigin="anonymous"></script>
</body>
</html>

blog/templates/category_detail.html
{% extends 'base.html' %}

{% block title %}
Glavnaya Stranitsa
{% endblock %}
{% block content %} 
<div class="container">
    <h2>Posti kategorii {{category.title}}</h2>
    <div class="row row-cols-1 row-cols-md-4 g-4">
        {% for post in category.post_set.all %}
        <div class="col">
          <div class="card">
            <img src="{{post.image.url}}" style="height: 200px; object-fit: cover;" class="card-img-top" alt="...">
            <div class="card-body">
              <a href="{{post.get_link}}">
                <h5 class="card-title">{{post.title}}</h5>
              </a>
              <p class="card-text">{{post.created_at|date:'d-F-Y'}}</p>
            </div>
          </div>
        </div>
        {% endfor %}
      </div>
</div>
{% endblock %}

blog/templates/index.html
{% extends 'base.html' %}

{% block title %}
Glavnaya Stranitsa
{% endblock %}
{% block content %} 
<div id="carouselExampleAutoplaying" class="carousel slide" data-bs-ride="carousel"> 

  <div class="carousel-inner">
    {% for slide in slides %}
    <div class="carousel-item {% if forloop.first %} active {% endif %}">
      <img src="{{slide.image.url}}" class="d-block w-100" height="500px" style="object-fit: cover; object-position: top;" alt="...">
      <div class="carousel-caption d-none d-md-block">
        <a href="{{post.get_link}}">
          <h5>{{slide.title}}</h5>
        </a>
      </div>
    </div>
    {% endfor %}
  </div>
  <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Previous</span>
  </button>
  <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Next</span>
  </button>
</div>
   
<div class="container">
  <h2>Poslednie novosti</h2>
  <hr>
  <div class="row row-cols-1 row-cols-md-4 g-4">
    {% for post in posts %}
    <div class="col">
      <div class="card">
        <img src="{{post.image.url}}" style="height: 200px; object-fit: cover;" class="card-img-top" alt="...">
        <div class="card-body">
          <a href="{{post.get_link}}">
            <h5 class="card-title">{{post.title}}</h5>
          </a>
          <p class="card-text">{{post.created_at|date:'d-F-Y'}}</p>
        </div>
      </div>
    </div>
    {% endfor %}
  </div>
  <hr>
  <h2>Kategorii</h2>
  <hr>
  <div class="row row-cols-1 row-cols-md-6 g-4">
    {% for category in categories %}
    <div class="col">
      <div class="card">
        <img src="{{category.image.url}}" style="height: 100px; object-fit: cover;" class="card-img-top" alt="...">
        <div class="card-body">
          <a href="{% url 'category_detail_url' category.slug %}">
            <h5 class="card-title">{{category.title}}</h5>
          </a>
        </div>
      </div>
    </div>
    {% endfor %}
  </div>
</div>
{% endblock %}

blog/templates/login.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
Vxod
{% endblock %}
{% block content %}
<div class="flex">
    <form action="{% url 'login_url' %}" method="POST" class="login">
        {% if message != null %}
        <div class="alert alert-danger">
            {{message}}
        </div>
        {% endif %}
        {% csrf_token %}
        <p>
            <input type="text" name="username" class="form-control" placeholder="Vash nickname">
        </p>
        <p>
            <input type="password" name="password" class="form-control" placeholder="Vash parol">
        </p>
        <p>
            <button class="btn btn-outline-success">Vxod</button>
        </p>
    </form>
</div>
{% endblock %}

blog/templates/post_detail.html
{% extends 'base.html' %}

{% block title %}
{{post.title}}
{% endblock %}

{% block content %}
<div class="container">
    <div class="img">
        <img src="{{post.image.url}}" alt="">
    </div>
    <div class="text">
        <h2>{{post.title}}</h2>
        <p>{{post.text}}</p>
        <p class="text-end">{{post.created_at|date:'d-F-Y'}}</p>
    </div>
    <div class="comment">
        {% if not user.is_authenticated %}
        <p>Вы не <a href="{% url 'login_url'%}">Вошли</a> в акаунт.
        Если вы не вошли в аккаунт то  <a href="{% url 'register' %}">Зарегистрироватся</a></p>
        {% else %}
        <form method="POST" action="{% url 'comment' post.slug %}">
            {% csrf_token %}
            <textarea name="comment" placeholder="Vash komentariy..." id="" class="form_control" ></textarea>
            <button class="btn btn-primary">Отправить</button>
        </form>
        {% endif %}
        <hr>
        {% for comment in post.comment_set.all%}
        <div class="single_comment">
            <h2>{{comment.author.username}}</h2>
            <hr>
            <p>{{comment.text}}</p>
            <p class="text-end">{{comment.date|timesince}}назад</p>
        </div>
        {% empty %}
        <p class="text-center">Коментариев нет</p>
        {% endfor %}
    </div>
</div>
{% endblock %}

blog/templates/register.html
{%extends 'base.html'%}
{% load static %}
{%block title%}
Registratsiya
{%endblock%}
{%block content%}
<div class="container">
    <div class="row">
        <div class="col-md-9">
            <form action="{% url 'register' %}" method="POST">
                {% csrf_token %}
                {{form.as_p}}
                <button class="btn btn-success">Registratsiya</button>
            </form>
        </div>
        <div class="col-md-3"></div>
    </div>
</div>
{%endblock%}

blog/templates/search.html
{% extends 'base.html' %}

{% block title %}
Poisk po zaprosu {{query}}
{% endblock %}
{% block content %} 
<div class="container">
    <h2>Posti po zaprosu {{query}}</h2>
    <div class="row row-cols-1 row-cols-md-4 g-4">
        {% for post in posts %}
        <div class="col">
          <div class="card">
            <img src="{{post.image.url}}" style="height: 200px; object-fit: cover;" class="card-img-top" alt="...">
            <div class="card-body">
              <a href="{{post.get_link}}">
                <h5 class="card-title">{{post.title}}</h5>
              </a>
              <p class="card-text">{{post.created_at|date:'d-F-Y'}}</p>
            </div>
          </div>
        </div>
        {% empty %}
        <p>Prostite poisk po zaprosu {{query}} ne dal rezultatov</p>
        {% endfor %}
      </div>
</div>

{% endblock %}